services:
  homarr:
    image: ajnart/homarr:latest
    container_name: homarr
    restart: unless-stopped
    ports:
      - "${HOMARR_PORT}:7575"
    environment: 
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - HOSTNAME=${HOMARR_HOSTNAME:-homarr}
      - DOMAIN=${HOMARR_DOMAIN:-doamaine.com}
    volumes:
      - ./homarr/configs:/app/data/configs
      - ./homarr/icons:/app/public/icons
      - ./homarr/data:/data
    networks:
      - homarr-net

networks:
  homarr-net:
    name: ${HOMARR_NETWORK_NAME:-homarr-net}
    driver: bridge