version: '3.8'

services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - ./configs:/app/data/configs
      - ./icons:/app/public/imgs/icons
      - ./data:/data
    environment:
      - TZ=${TZ}
      - BASE_URL=${BASE_URL}
      - DOCKER_HOST=${DOCKER_HOST}
      - DOCKER_SOCKET=/var/run/docker.sock
    ports:
      - "${PORT}:7575"
    networks:
      - homarr_net

networks:
  homarr_net:
    driver: bridge