services:
  homarr:
    image: ghcr.io/ajnart/homarr:latest
    container_name: homarr
    ports:
      - "7575:7575" # Port pour accéder au dashboard
    volumes:
      - ./data:/app/data # Stockage persistant pour les données et configurations
      - ./public:/app/public # Dossier public pour personnaliser l'apparence
    environment:
      - TZ=${TIMEZONE}
      - BASE_URL=${BASE_URL}
    restart: unless-stopped
    networks:
      - homarr_net

networks:
  homarr_net:
    driver: bridge