services:
  homarr:
    container_name: ${HOSTNAME:-homarr}
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./configs:/app/data/configs
      - ./icons:/app/public/icons
      - ./data:/data
    environment:
      - TZ=${TZ:-Europe/Paris}
      - PASSWORD=${HOMARR_PASSWORD}
      - BASE_URL=${BASE_URL:-http://localhost:7575}
      - DISABLE_ANALYTICS=${DISABLE_ANALYTICS:-true}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - HOSTNAME=${HOSTNAME:-homarr}
      - DOMAIN=${DOMAIN}
    ports:
      - "${PORT:-7575}:7575"
    networks:
      - homarr-net

networks:
  homarr-net:
    name: ${NETWORK_NAME:-homarr-net}
    driver: bridge