services:
  homarr:
    image: ghcr.io/ajnart/homarr:latest
    container_name: homarr
    restart: unless-stopped
    ports:
      - "${HOMARR_PORT}:7575"
    environment: 
      - LOG_LEVEL=${LOG_LEVEL:-info}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./configs:/app/data/configs
      - ./imgs:/app/public/imgs
      - ./data:/data
    networks:
      - homarr-net

networks:
  homarr-net:
    name: ${HOMARR_NETWORK_NAME:-homarr-net}
    driver: bridge