services:
  homeassistant:
    container_name: home-assistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=${TZ}
    restart: unless-stopped
    ports:
     - ${HOME_ASSISTANT_PORT}:8123
    networks:
      - home-assistant

  homeassistant-db:
    image: postgres:16.3
    container_name: homeassistant-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - home-assistant
      
  esphome:
    container_name: esphome
    image: esphome/esphome
    volumes:
      - ./esphome:/config
    ports:
      - "${ESPHOME_PORT}:6052"
    restart: unless-stopped
    networks:
      - home-assistant
  
  file-editor:
    container_name: file-editor
    image: ghcr.io/hassio-addons/file-editor
    volumes:
      - ./config:/config
    ports:
      - "${FILE_EDITOR_PORT}:8080"
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=${TZ}
    restart: unless-stopped
    networks:
      - home-assistant


networks:
  home-assistant:
