services:
  homeassistant:
    container_name: home-assistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=${TZ}
    restart: unless-stopped
    ports:
     - 8123:8123
    networks:
      - home-assistant

  homeassistant-db:
    image: postgres:16.3
    container_name: homeassistant-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - home-assistant
      
  esphome:
    container_name: esphome
    image: esphome/esphome
    volumes:
      - ./esphome:/config
    ports:
      - "6052:6052"
    restart: unless-stopped
    networks:
      - home-assistant


networks:
  home-assistant:
